### Specifying language
language: python

### Test Python versions
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

### Command to install dependencies
install:
  - pip install -U pip
  - python setup.py install

### Command to run tests
script: pytest